<a href="https://colab.research.google.com/github/kenhuangsy/learning-tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we are going to cover the fundamental concepts of tensorflow.

We are going to cover:


*   Introduction to  tensors
*   Getting information from tensors
*   Manipulating tensors
*   tensors and numpy
*   Using @tf.function
*   Using GPUs with tensorflow (or TPUs)


## Introduction to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)


2.8.2


In [2]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#Check the number of dimensions of a tensor (ndim = number of dimensions)
scalar.ndim


0

In [4]:
#create a vector
vector = tf.constant([10, 10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [5., 6.]]) #specify data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  6.]], dtype=float32)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                        [10,11,12]],
                        [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

Scalar = a single number
Vector = a number with direction
Matrix = 2 dimensional array of numbers
Tensor = n-dimensional array of numbers where n can be from 0 to infinity => n = 0 -> scalar, n = 2 -> matrix

In [12]:
#Create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#Change one of the elements in changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Creating Random Tensors

In [14]:
#Creating random tensors
#Random tensors are tensors of some arbitrary size which contain random numbers
#Useful for creating random weights
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in a tensor

Valuable for when you want to shuffle your data so the inherent order doesn't affect learning.
If we want our shuffled tensors to be in the same order, we have to set the global level random seed as well as the operation level random seed

In [15]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim


2

In [16]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
#Shuffle
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

Exercise: Write 5 random tensors and shuffle them

In [18]:
random_tensor_1 = tf.random.Generator.from_seed(42)
random_tensor_1 = random_tensor_1.normal(shape=(3,2))
random_tensor_1_shuffled = tf.random.shuffle(random_tensor_1, seed = 42)
random_tensor_1, random_tensor_1_shuffled

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193765, -1.8107855 ],
        [ 0.07595026, -1.2573844 ],
        [-0.7565803 , -0.06854702]], dtype=float32)>)

In [19]:
random_tensor_2 = tf.random.Generator.from_seed(42)
random_tensor_2 = random_tensor_2.normal(shape=(10,5))

random_tensor_2_shuffled = tf.random.shuffle(random_tensor_2, seed = 42)
random_tensor_2, random_tensor_2_shuffled

(<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 , -0.5716629 ],
        [ 0.1480774 , -0.23362991, -0.3522796 ,  0.40621266, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.44629744, -2.3410842 ,  0.99009085],
        [-0.08763231, -0.635568  , -0.6161736 , -1.9441465 , -0.48293006],
        [-0.5244748 , -1.0345329 ,  1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034, -0.30288252, -1.443651  ],
        [ 1.0034493 ,  0.20857747,  0.35700995,  1.0648885 ,  1.2432486 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ,  0.01380118, -0.24827152]],
       dtype=float32)>, <tf.Tensor: shape=(10, 5), dtype=float32, numpy=
 array([[-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 , -0.5716629 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ,  0.

In [20]:
random_tensor_3 = tf.random.Generator.from_seed(42)
random_tensor_3 = random_tensor_3.normal(shape = (2, 5))

random_tensor_3_shuffled = tf.random.shuffle(random_tensor_3)
random_tensor_3, random_tensor_3_shuffled

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 , -0.5716629 ]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 , -0.5716629 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765]],
       dtype=float32)>)

In [21]:
random_tensor_4 = tf.random.Generator.from_seed(42)
random_tensor_4 = random_tensor_4.normal(shape = (4,2))

random_tensor_4_shuffled = tf.random.shuffle(random_tensor_4)
random_tensor_4, random_tensor_4_shuffled

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[ 0.07595026, -1.2573844 ],
        [-0.7565803 , -0.06854702],
        [ 0.09988727, -0.50998646],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [22]:
tf.random.set_seed(42) #global level random seed

random_tensor_5 = tf.random.Generator.from_seed(42) #Operation level random seed
random_tensor_5 = random_tensor_5.normal(shape = (5,6))

random_tensor_5_shuffled = tf.random.shuffle(random_tensor_5, seed = 42)

random_tensor_5, random_tensor_5_shuffled

(<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765,
         -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 , -0.5716629 ,  0.1480774 ,
         -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ,  1.2054597 ,  1.6874489 ,
         -0.44629744],
        [-2.3410842 ,  0.99009085, -0.08763231, -0.635568  , -0.6161736 ,
         -1.9441465 ],
        [-0.48293006, -0.5244748 , -1.0345329 ,  1.3066901 , -1.5184573 ,
         -0.4585211 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 6), dtype=float32, numpy=
 array([[-2.3410842 ,  0.99009085, -0.08763231, -0.635568  , -0.6161736 ,
         -1.9441465 ],
        [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765,
         -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 , -0.5716629 ,  0.1480774 ,
         -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ,  1.2054597 ,  1.6874489 ,
         -0.44629744],
        [-0

## Other methods of creating tensors

In [23]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
#Create a tensor of all zeros
tf.zeros(shape = (2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

The main difference is that tensors can be run on a GPU (much faster for numerical computing)

In [25]:
#You can also turn NumPy arrays to tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) #create a numpy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(numpy_A, shape = (2,3,4)) #2*3*4 = 24
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [27]:
A.ndim

3

In [28]:
C = tf.constant(numpy_A, shape = (2, 12))
C

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

## Getting information from tensors

* Shape = the length (number of elements of each of the dimensions of a tensor => tensor.shape
* Rank = the number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n => tensor.ndim
* Axis or Dimension = a particular dimension of a tensor => tensor[0], tensor[:,1]
* Size = the total number of items in the tensor => tf.size(tensor)

In [29]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [31]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
2*3*4*5 #tf.size

120

In [33]:
#Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of our tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of our tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


## Indexing tensors

tensors can be indexed just like python lists

In [34]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
#Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [37]:
# create a rank 2 tensor
tf.random.set_seed(42)
rank_2_tensor = tf.random.Generator.from_seed(42).normal(shape=(2,2))
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [38]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [39]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.06854702, -1.2573844 ], dtype=float32)>

In [40]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

In [41]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

In [42]:
tf.expand_dims(rank_2_tensor, axis = 0) #expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]]], dtype=float32)>

## Manipulating tensors (tensor operations)

In [43]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:
tensor*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [45]:
tensor-1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [46]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [47]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

##Matrix Multiplication

In [48]:
# Matrix Multiplication in Tensorflow
display(tensor)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [49]:
tensor * tensor # this is element wise so it yields different results

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [50]:
# Matrix multiplication with python operator "@"
t1 = tf.constant([[1,2,5],
                [7,2,1],
                [3,3,3]])
t2 = tf.constant([[3,5],
                  [6,7],
                  [1,8]])
t1 @ t2 #same thing for matrix multiplication

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [51]:
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
Y


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [52]:
tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

##The Dot Product
Matrix multiplication is also referred to as the dot product. 

You can perform matrix multiplication using:
* 'tf.matmul()'
* 'tf.tensordot()'

In [53]:
#Perform the dot product on X and Y (requires X or Y to be transposed)
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [54]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [55]:
#Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [56]:
#Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [57]:
#Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y, (2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication ⌨

##Changing the datatype of a tensor

In [58]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [59]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [60]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [61]:
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [62]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

##Aggregating Tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [63]:
# Get the absolute values
D = tf.constant([-7,-10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Let's go through the following forms of aggregation: 
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [64]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 4,  4, 52, 85, 64, 15, 30, 78, 91, 69, 87, 12, 81, 31, 51, 28, 42,
       39, 85, 98, 17, 40, 94, 36, 27, 25, 46,  6,  3, 15, 63, 72, 59, 33,
       73, 20, 97, 82, 65, 39, 14, 48, 68, 32, 93, 59, 81, 25, 15, 92])>

In [65]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [66]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [67]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [68]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [69]:
# Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2485>

***Exercise:***Find the variance and standard deviation of E tensor using TensorFlow methods

In [70]:
# Find the variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=856>

In [71]:
# Get the standard deviation
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.251497>

In [72]:
# Find the variance
tf.math.reduce_variance(tf.cast(E, dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=855.5>

## Find the positional maximum and minimum of a tensor

In [73]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [74]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [75]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [76]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [78]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [79]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimensions)

In [80]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [81]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [82]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## One-Hot Encoding Tensors

In [83]:
 # Create a list of indices
some_list = [0,1,2,3] # Could be red, green, blue, purple

#One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## Squaring, log, square root

In [84]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [85]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [86]:
# Find the square root
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [87]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy
tensorflow interacts beautifully with numpy arrays. Tensors can be run on GPUs or TPUs for faster computing unlike NumPy arrays.

In [88]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [89]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [90]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [91]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [92]:
# The defualt types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Finding access to GPUs

In [94]:
tf.config.list_physical_devices() #We are currently using CPU

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [93]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [96]:
!nvidia-smi

Sun Sep 18 03:32:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    27W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to a CUDA-enabled GPU, Tensorflow will automatically use it whenever possible.

## End of Course Exercises

In [98]:
#1. Create a vector, scalar, matrix, and tensor with values of your choosing using tf.constant()

scalar = tf.constant(5)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tensor = tf.constant([[[3,4,5,6],
                       [5,2,5,4],
                       [44,5,6,7]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
 array([[[ 3,  4,  5,  6],
         [ 5,  2,  5,  4],
         [44,  5,  6,  7]]], dtype=int32)>)

In [99]:
print("shape of tensor:", tensor.shape)
print("rank of tensor:", tf.rank(tensor))
print("size of tensor:", tf.size(tensor))

shape of tensor: (1, 3, 4)
rank of tensor: tf.Tensor(3, shape=(), dtype=int32)
size of tensor: tf.Tensor(12, shape=(), dtype=int32)


In [115]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300]
tf.random.set_seed(42)

tensor_1 = tf.random.uniform(shape=(5,300), dtype = tf.float16)
tensor_2 = tf.random.uniform(shape=(5,300), dtype = tf.float16)

tensor_1,tensor_1.shape,tensor_2,tensor_2.shape


(<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.0928 , 0.7275 , 0.8135 , ..., 0.1455 , 0.624  , 0.02637],
        [0.3408 , 0.3252 , 0.03906, ..., 0.964  , 0.3955 , 0.747  ],
        [0.4727 , 0.1084 , 0.2158 , ..., 0.6436 , 0.7715 , 0.535  ],
        [0.577  , 0.2783 , 0.3887 , ..., 0.8467 , 0.552  , 0.955  ],
        [0.3613 , 0.00879, 0.718  , ..., 0.3408 , 0.4941 , 0.549  ]],
       dtype=float16)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.2051 , 0.8506 , 0.706  , ..., 0.4883 , 0.12305, 0.9316 ],
        [0.1445 , 0.962  , 0.291  , ..., 0.8564 , 0.6377 , 0.02148],
        [0.3867 , 0.999  , 0.927  , ..., 0.9326 , 0.5635 , 0.05957],
        [0.789  , 0.4307 , 0.2031 , ..., 0.8545 , 0.9434 , 0.02344],
        [0.6836 , 0.749  , 0.7275 , ..., 0.463  , 0.9023 , 0.2568 ]],
       dtype=float16)>,
 TensorShape([5, 300]))

In [117]:
#Multiply the two tensors using matrix multiplication
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[70.2 , 68.75, 68.6 , 67.25, 76.4 ],
       [75.75, 76.06, 74.7 , 76.  , 81.1 ],
       [77.25, 78.06, 71.56, 76.7 , 81.1 ],
       [74.8 , 77.3 , 67.94, 76.  , 78.7 ],
       [76.4 , 76.44, 74.  , 72.4 , 79.4 ]], dtype=float16)>

In [119]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor_3 = tf.random.uniform(shape = (224,224,3), dtype = tf.float16)
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float16, numpy=
array([[[0.9707  , 0.2168  , 0.3008  ],
        [0.949   , 0.06836 , 0.838   ],
        [0.9805  , 0.1719  , 0.4355  ],
        ...,
        [0.46    , 0.2588  , 0.4326  ],
        [0.0967  , 0.74    , 0.04883 ],
        [0.5664  , 0.6543  , 0.8594  ]],

       [[0.5615  , 0.4043  , 0.06836 ],
        [0.10156 , 0.5176  , 0.287   ],
        [0.331   , 0.5576  , 0.7188  ],
        ...,
        [0.3047  , 0.166   , 0.8623  ],
        [0.7354  , 0.252   , 0.8477  ],
        [0.012695, 0.4932  , 0.4902  ]],

       [[0.7334  , 0.08887 , 0.949   ],
        [0.703   , 0.665   , 0.628   ],
        [0.871   , 0.124   , 0.671   ],
        ...,
        [0.04785 , 0.255   , 0.1621  ],
        [0.577   , 0.9033  , 0.7656  ],
        [0.877   , 0.573   , 0.6494  ]],

       ...,

       [[0.4756  , 0.8936  , 0.992   ],
        [0.9355  , 0.1602  , 0.334   ],
        [0.375   , 0.3447  , 0.249   ],
        ...,
        [0.907   , 0.6494  , 0.805

In [121]:
tf.reduce_min(tensor_3), tf.reduce_max(tensor_3)

(<tf.Tensor: shape=(), dtype=float16, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=0.999>)

In [124]:
#Created a tensor with random values of shape [1, 224, 224, 3] 
#then squeeze it to change the shape to [224, 224, 3].
tensor_4 = tf.random.uniform(shape=(1,224,224,3), dtype = tf.float16)
tf.squeeze(tensor_4).shape

TensorShape([224, 224, 3])

In [127]:
# Create a tensor with shape [10] using your own choice of values,
# then find the index which has the maximum value.
tensor_5 = tf.range(10) 
max_index = tf.math.argmax(tensor_5)
tensor_5, max_index, tensor_5[max_index]

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [130]:
# One hot encode the tensor
tf.one_hot(tf.cast(tensor_5, dtype = tf.int32), depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

## Go through the TensorFlow 2.x quick start for beginners 

In [132]:
tf.__version__

'2.8.2'

In [133]:
#Load the MNIST dataset
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0


11501568/11490434 [==============================] - 0s 0us/step


In [134]:
X_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [135]:
# Build a machine learning model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [137]:
predictions = model(X_train[:1]).numpy()
predictions

array([[-0.18957113, -0.36001056, -0.19964263, -0.29784447, -0.3219071 ,
         0.25118774,  0.40335578,  0.01726946, -0.16932344, -0.20461935]],
      dtype=float32)

In [138]:
tf.nn.softmax(predictions).numpy()

array([[0.08924452, 0.07525939, 0.08835021, 0.08008645, 0.07818237,
        0.13867582, 0.16146801, 0.10975172, 0.09106994, 0.08791161]],
      dtype=float32)

In [139]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [140]:
loss_fn(y_train[:1], predictions).numpy()

1.9756162

In [141]:
model.compile(optimizer='adam',
              loss = loss_fn,
              metrics=['accuracy'])

In [142]:
model.fit(X_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2944 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1421 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1047 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0855 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0731 - accuracy: 0.9767


In [143]:
model.evaluate(X_test, y_test, verbose = 2)

313/313 - 1s - loss: 0.0750 - accuracy: 0.9764 - 799ms/epoch - 3ms/step


[0.07497153431177139, 0.9764000177383423]

In [144]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [145]:
probability_model(X_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.05662636e-07, 1.66460211e-07, 4.31268672e-05, 5.09743404e-05,
        7.67670909e-12, 7.58494352e-08, 1.18612203e-11, 9.99905109e-01,
        1.22300023e-07, 1.91876495e-07],
       [1.23743447e-07, 2.07375197e-05, 9.99975801e-01, 1.65514189e-06,
        1.23706953e-13, 1.86804087e-07, 7.59921193e-07, 7.05506236e-15,
        6.94508287e-07, 4.51812004e-10],
       [3.04894161e-06, 9.97584343e-01, 4.35530819e-04, 9.01650128e-06,
        5.91981552e-05, 4.97835481e-06, 3.76640746e-05, 1.44899602e-03,
        4.14924027e-04, 2.29103375e-06],
       [9.99539614e-01, 7.34932684e-08, 2.64913368e-04, 3.72257034e-07,
        3.01379004e-07, 1.98578073e-06, 1.74596295e-04, 2.14696706e-06,
        7.23790849e-09, 1.59312240e-05],
       [4.65798621e-06, 6.36073016e-09, 1.97296722e-05, 9.59993862e-09,
        9.96941984e-01, 2.66344074e-07, 8.43891144e-07, 7.72108397e-05,
        9.83514155e-07, 2.95433984e-03]], dtype=float32)>